server:
  port: 8080
debug: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mc_authentication
    username: mcuser
    password: mcuser
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  flyway:
    enabled: true
    baselineOnMigrate: true
    schemas: public

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 206852461579613
            clientSecret: d509b2331ffd4a4ccb8faf803779c7fe
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  base-url: http://localhost:8080
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
    sessionAuthTokenName: "dei-www"
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    # After successfully authenticating with the OAuth2 Provider,
    # we'll be generating an auth token for the user and sending the token to the
    # redirectUri mentioned by the client in the /oauth2/authorize request.
    # We're not using cookies because they won't work well in mobile clients.
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

  message:
    email:
      mailgun:
        domains: "sandbox54d5cde9529947a98f6b72b63096812a.mailgun.org"
        api-url: "https://api.mailgun.net/v3/"
        api-key: "dea3df8a018ca20a51e4258732b3b536-fe066263-9793037e"
        from:
          name: "mc team"
          email: "tomo.landeka02@gmail.com"
  gui:
    base-url: "localhost:3000"
    recovery-route: "${app.gui.base-url}/reset-password/?recoveryCode="
    confirmation-route: "${app.gui.base-url}/register/confirm/?confirmationCode="
